"use client";
import { Container } from "@mui/material";
import Navbar from "./components/navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Container maxWidth={"xl"}>{children}</Container>
      </body>
    </html>
  );
}
